// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD435JGO-TZ4-klFalywEWEJrhYJo3G3q8',
    appId: '1:71260631222:web:c5713128fd087c6f9d7617',
    messagingSenderId: '71260631222',
    projectId: 'creators-rent-app',
    authDomain: 'creators-rent-app.firebaseapp.com',
    storageBucket: 'creators-rent-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBmdybctOg93w6GJx4pLDwpUzTU-xS5lw',
    appId: '1:71260631222:android:8e598d8e35284a0c9d7617',
    messagingSenderId: '71260631222',
    projectId: 'creators-rent-app',
    storageBucket: 'creators-rent-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvRlBR_T-uJz-HqhhK3vh2PiBOg3-VBtw',
    appId: '1:71260631222:ios:2271d92a05e4fae59d7617',
    messagingSenderId: '71260631222',
    projectId: 'creators-rent-app',
    storageBucket: 'creators-rent-app.firebasestorage.app',
    iosBundleId: 'com.example.rentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvRlBR_T-uJz-HqhhK3vh2PiBOg3-VBtw',
    appId: '1:71260631222:ios:2271d92a05e4fae59d7617',
    messagingSenderId: '71260631222',
    projectId: 'creators-rent-app',
    storageBucket: 'creators-rent-app.firebasestorage.app',
    iosBundleId: 'com.example.rentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD435JGO-TZ4-klFalywEWEJrhYJo3G3q8',
    appId: '1:71260631222:web:b5d2552c8963f07f9d7617',
    messagingSenderId: '71260631222',
    projectId: 'creators-rent-app',
    authDomain: 'creators-rent-app.firebaseapp.com',
    storageBucket: 'creators-rent-app.firebasestorage.app',
  );
}
